apiVersion: apps/v1
kind: Deployment
metadata:
  name: plantech-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plantech-backend
  template:
    metadata:
      labels:
        app: plantech-backend
    spec:
      containers:
      - name: plantech-backend
        image: plantech-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_URL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASS
        - name: JWT_SECRET
          value: "c3VwZXItc2VjcmV0LWZvci1wbGFudGVjaC1hcHAtMjAyNS1sb25nLWFuZC1zdHJvbmc="